### PR TITLE
Don't make native constructor inherit from EE.

### PR DESCRIPTION
**Pull request by bnoordhuis**
Prototypical inheritance doesn't work the same way for a constructor
that is backed by a v8::ObjectTemplate instance.  Don't expose the
native object directly, return a stub instead.

Don't take as-is, this is just to illustrate the point.

### CODE REVIEW

**Comment by bajtos** [comment]
Thank you Ben. Closing in favour of https://github.com/pipobscure/fsevents/pull/45

**Comment by es128** [comment]
Any chance either of you might offer to take over maintenance of the fsevents module (or know someone else who has the requisite skills and may be interested)?

I'm pretty sure Philipp would still be receptive to the idea (https://github.com/pipobscure/fsevents/pull/38#issuecomment-60560598), but I personally do not have enough background in C to be qualified to properly do it myself.

**Comment by bnoordhuis** [comment]
@es128 I think we would be open to putting it under the strongloop umbrella, like we did with express and other projects.  If you think that's an option, let me know and I'll bring it up internally.  I doubt that fsevents is a high maintenance project so it's probably not a big deal.

**Comment by es128** [comment]
@pipobscure ultimately it's up to you. Are you interested in handing it off to strongloop?

**Comment by pipobscure** [comment]
@bnoordhuis I'd be Glas for StrongLoop to take The reigns. My own work has sadly taken me away from both Mac and Node/IO.js though I continue to enjoy them privately. In consequence I no longer have the luxury to maintain at will.

**Comment by bnoordhuis** [comment]
@pipobscure Cheers!  If you transfer the project to the strongloop org and add strongloop as a maintainer on npm, @bajtos and me can take it from there.  Thanks!

**Comment by pipobscure** [comment]
@bnoordhuis @bajtos I did the owner add in npm, but github refused the transfer since I obviously don't have admin rights to that org. But then since git is a DISTRIBUTED versioning system with no authoritative repo, I guess npm is all you need :smile:

**Comment by bajtos** [comment]
@pipobscure it would be best if you could contact GitHub support to arrange the transfer. That way the issues will be preserved, the URL to repo under your username will redirect to Strongloop org, etc. From my past experience, they resolve such requests pretty quickly.

**Comment by sindresorhus** [comment]
@pipobscure Just transfer the repo to @bnoordhuis, and he can transfer it into the org ;)

**Comment by pipobscure** [comment]
I would have, but he already has a fork, which prevents the transfer. I'm getting in touch with github support now.

**Comment by bnoordhuis** [comment]
@pipobscure I've deleted my fork.

**Comment by pipobscure** [comment]
I just did the transfer to you. Cheers!

**Comment by bnoordhuis** [comment]
Thanks @pipobscure!

**Pull request closed without merging**
